#!/bin/bash

#First of all I check if the dir exists. If not I create it
if [ ! -d $OPENSHIFT_DATA_DIR'images_uploaded' ]
then
    echo "Create "$OPENSHIFT_DATA_DIR'images_uploaded'
    mkdir -p $OPENSHIFT_DATA_DIR'images_uploaded'
fi

#Create symlink
echo "Create link: "$OPENSHIFT_REPO_DIR'images_uploaded -> '$OPENSHIFT_DATA_DIR'images_uploaded'
ln -sf $OPENSHIFT_DATA_DIR'images_uploaded' $OPENSHIFT_REPO_DIR'images_uploaded'
